export const LOGIN_USER_REQ = "LOGIN_USER_REQ"
export const GET_ACCOUNT_ACTIVITY = "GET_ACCOUNT_ACTIVITY"
export const ACCOUNT_ACTIVITY = "ACCOUNT_ACTIVITY"
export const LOGIN_USER_RESPONSE = "LOGIN_USER_RESPONSE"
export const LOGOUT_ACTIVITY = "LOGOUT_ACTIVITY"


export const ADD_NEW_INVESTMENT = "ADD_NEW_INVESTMENT"
export const GET_ALL_INVESTMENT_REQ = "GET_ALL_INVESTMENT_REQ"
export const ALL_INVESTMENT_LIST = "ALL_INVESTMENT_LIST"


export const GLOBAL_SETTING_REQ = "GLOBAL_SETTING_REQ"
export const GLOBAL_SETTING = "GLOBAL_SETTING"

export const ADD_NESTED_SETTING = "ADD_NESTED_SETTING"
export const NESTED_SETTING_REQ = "NESTED_SETTING_REQ"
export const NESTED_SETTING_LIST = "NESTED_SETTING_LIST"
